OPENAI_API_KEY = "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"
openai_api_key = "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"
COHERE_API_KEY = "N3m2VncWlG6czPuQIyOQtCk5Wz91GKI29t5ry1Or"
url1 = "https://api1-query-dataset-server-4qvwqvpl5a-wl.a.run.app/api1/clickcarquery"
url2 = "https://api2-gpt4salesperson-server-4qvwqvpl5a-wl.a.run.app/api2/salespersonquery"
url3 = "https://api3-precision-clickcar-rag-4qvwqvpl5a-wl.a.run.app/api3/clickcarquery"
BROWSERLESS_API_KEY = 'bc725601-6455-4e35-bfe1-eadc59ff4104'
